lr: 0.01
epoch=2, accuracy=0.5311958275063068, loss=0.5462571801698768
epoch=3, accuracy=0.5770187346016662, loss=0.49816277707060924
epoch=4, accuracy=0.7244618636398443, loss=0.32406454573591315
epoch=5, accuracy=0.8136540458340896, loss=0.2785895298912673
epoch=6, accuracy=0.7728565529432286, loss=0.12697897832344268
epoch=7, accuracy=0.7716481220609013, loss=0.10790416359249613
epoch=8, accuracy=0.8717955166000493, loss=0.11637631030992442
epoch=9, accuracy=0.8818570223579603, loss=0.1250571506458179
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/u3/oqcardos/.local/lib/python3.11/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
/u3/oqcardos/.local/lib/python3.11/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
/u3/oqcardos/.local/lib/python3.11/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
